---
- name: extract paperless-ng
  unarchive:
    src: "https://github.com/paperless-ngx/paperless-ngx/releases/download/ngx-{{ paperlessngx_version }}/paperless-ng-{{ paperlessngx_version }}.tar.xz"
    remote_src: yes
    dest: "{{ tempdir.path }}"
